[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  # Les variables d'environnement seront définies dans l'interface Netlify
  # Ne pas mettre de valeurs réelles ici pour des raisons de sécurité

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
