[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  REACT_APP_SUPABASE_URL = "${REACT_APP_SUPABASE_URL}"
  REACT_APP_SUPABASE_ANON_KEY = "${REACT_APP_SUPABASE_ANON_KEY}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
